### ISSUE TITLE
Scaladoc outdated

### ISSUE THREAD

**Issue by aij** [squeryl/squeryl#203]
It seems like the scaladoc has fallen out of date.

For example, [the sources](https://github.com/squeryl/squeryl/blob/b66633c48de420e0fc00823d10aa152b015a4ae6/src/main/scala/org/squeryl/dsl/CompositeKey.scala#L92) show a public `in` method on `CompositeKey2` but the [scaladoc](http://squeryl.org/api/index.html#org.squeryl.dsl.CompositeKey2) does not.

**Comment by davewhittaker** [comment]
@aij The scaladoc is for the 0.9.5 series, which is still the "official" release.  When 0.9.6 is released we'll bring that up to date.
