### ISSUE TITLE
how to write json or jsonb on postgresql

### ISSUE THREAD

**Issue by wanghuatao** [squeryl/squeryl#207]
the error

Caused by: org.postgresql.util.PSQLException: ERROR: column "data" is of type jsonb but expression is of type character varying
 ：You will need to rewrite or cast the expression.

**Comment by davewhittaker** [comment]
The error you posted is generated by postgresql itself, and without any context it's difficult to help you.  Regardless, this doesn't seem like a bug.  If you'd like help, I'd suggest that you reach out with some more information about what led to the error on [the mailing list](https://groups.google.com/forum/#!forum/squeryl)

**Comment by wanghuatao** [comment]
sorry my pool english。this is my code:

class RoleData( var roleId: String, var data: String)
object Library extends Schema {
  val roleData = table[RoleData]
  on(roleData)(s => declare(
    s.roleId is(primaryKey, indexed),
    s.data is (dbType("jsonb"))
  ))

when i call :
roleData.insert(new RoleData("id3",jsonb))
the error happend.so ,my question is how to insert a jsonb string

**Comment by davewhittaker** [comment]
I'd be happy to help you out, but as I suggested, this type of discussion should be had on the mailing list, not as a Github issue.  Please repost there.
