### ISSUE TITLE
Is squeryl still alive? 

### ISSUE THREAD

**Issue by xuwei-k** [squeryl/squeryl#215]
I need some updates because we use squeryl in production.
Could you add me as a maintainer?  @max-l @davewhittaker

**Comment by pbrant** [comment]
Hi Kenji, I've gone ahead and merged your outstanding PRs. I only have member permission on the project so I can't add you as an owner (and I'd prefer @max-l do that anyway), but I'm happy to merge PRs.

(By the way, it looks like the 2.12 build is currently broken

sbt.ResolveException: unresolved dependency: org.scalatest#scalatest_2.12.0-M4;3.0.0: not found

)

**Comment by xuwei-k** [comment]
> By the way, it looks like the 2.12 build is currently broken

I just submit a pull request https://github.com/squeryl/squeryl/pull/216

**Comment by davewhittaker** [comment]
@xuwei-k @pbrant I just posted on the Squeryl list.  I'm hoping we can have a bit of a discussion about the future of the project there.  https://groups.google.com/forum/#!topic/squeryl/MCqM4wY7ZP8
