### ISSUE TITLE
please release new version

### ISSUE THREAD

**Issue by xuwei-k** [squeryl/squeryl#217]
last release is 2 years ago https://github.com/squeryl/squeryl/releases
I think it's time to new release.

**Comment by xuwei-k** [comment]
https://issues.sonatype.org/browse/OSSRH-2789?focusedCommentId=374192&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-374192

I have request access. I will release a new version in a few days if there is no objections.

**Comment by xuwei-k** [comment]
0.9.7 released

- https://github.com/squeryl/squeryl/releases/tag/0.9.7
- https://oss.sonatype.org/content/repositories/releases/org/squeryl/squeryl_2.12.0-RC1/0.9.7/
- https://oss.sonatype.org/content/repositories/releases/org/squeryl/squeryl_2.11/0.9.7/
- https://oss.sonatype.org/content/repositories/releases/org/squeryl/squeryl_2.10/0.9.7/

**Comment by davewhittaker** [comment]
@xuwei-k We actually hadn't released a 0.9.6 final.  The last 0.9.6 sent to maven was RC4 in October of 2015.  It's good to have gotten this out though.  When I have a moment I'll post soething on the list to let people know about the version jump.
