### ISSUE TITLE
Improperly published JAR file for version 0.9.5-7 on Bintray

### ISSUE THREAD

**Issue by kflorence** [squeryl/squeryl#225]
I wanted to make you aware that Bintray currently has an improperly cached JAR file that caused us quite a headache.

From Bintray: https://jcenter.bintray.com/org/squeryl/squeryl_2.11/0.9.5-7/:squeryl_2.11-0.9.5-7.jar
`MD5 (squeryl_2.11-0.9.5-7.jar) = b01067f9e499c3699233dcb25be192bb`

From Maven: http://repo1.maven.org/maven2/org/squeryl/squeryl_2.11/0.9.5-7/squeryl_2.11-0.9.5-7.jar
`MD5 (squeryl_2.11-0.9.5-7.jar) = da0bb64b6056ddbbb82b3699a6b6b287`

Through debugging, we found that this line was different in the two JARs: https://github.com/squeryl/squeryl/blob/0.9.5-7/src/main/scala/org/squeryl/internals/FieldMetaData.scala#L626

It was manifesting itself as a "could not map row with mapper" error where it was trying to map `null` to `BigDecimal`.

**Comment by kflorence** [comment]
Specifically, it looks like this commit was not included in the Bintray version: https://github.com/squeryl/squeryl/commit/1d6931fd03fa8b2dc0efb77b54748b796a2c885f

**Comment by davewhittaker** [comment]
Hmm... thanks for the heads up.  I'm not sure how that could happen though, we don't publish directly to bintray and that JAR file was published in 2014.
