### ISSUE TITLE
Allow specifying (ps: PreparedStatement, colIdx: Int)=>Unit function in Typed Expression Factory

### ISSUE THREAD

**Issue by AEtherSurfer** [squeryl/squeryl#228]
I have a desire to set Calendar on a [setTimestamp](https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setTimestamp-int-java.sql.Timestamp-java.util.Calendar-) call on the `PreparedStatement` for a custom Date type.

Please allow me to specify a function that operates on the prepared statement instead of merely calling setObject(idx, convertedJdbcValue))

References: https://github.com/squeryl/squeryl/blob/master/src/main/scala/org/squeryl/internals/DatabaseAdapter.scala
http://stackoverflow.com/questions/41642922/how-do-i-ensure-a-date-is-stored-as-utc

**Comment by davewhittaker** [comment]
Please do not report things that are not Squeryl bugs through Github issues.  If you'd like to bring this up on Github, I'd suggest a pull request.

**Comment by AEtherSurfer** [comment]
How should I submit feature requests?

**Comment by davewhittaker** [comment]
Right now, there is no one I'm aware of who is actively looking to add features based on community requests.   You are welcome to bring it up on the mailing list to see if you can grab someone's attention, but your best bet is to implement a fix yourself and create a pull request.
